name: Deploy 

on:
  push:
    branches: [ "master" ]

jobs:
  laravel-tests:
    name: crete deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Compile CSS and Javascrip
     run:
      npm install
      npm run prod
